/**
|--------------------------------------------------
| Action Types
|--------------------------------------------------
*/

//login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERRORS = "LOGIN_ERRORS";
export const LOGINED_USER = "LOGINED_USER";
//register
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const REGISTERD_USER = "REGISTERD_USER";
export const VERIFED_USER = "VERIFED_USER";
export const VERIFY_LOADING = "VERIFY_LOADING";
export const CLEAR_REGISTER_ERRORS = "CLEAR_REGISTER_ERRORS";
//user
export const USER_LOADING = "USER_LOADING";
export const AUTH_USER = "AUTH_USER";
export const NETWORK_ERROR = "NETWORK_ERROR";
//product
export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FIND_PRODUCT = "FIND_PRODUCT";
export const PRODUCT_ERRORS = "PRODUCT_ERRORS";
export const CLEAR_PRODUCT_ERRORS = "CLEAR_PRODUCT_ERRORS";
export const SET_CART_PRODUCT = "SET_CART_PRODUCT";
export const DEL_CART_PRODUCT = "DEL_CART_PRODUCT";
export const GET_CART_PRODUCT = "GET_CART_PRODUCT";
export const CLEAR_CART_PRODUCT = "CLEAR_CART_PRODUCT";
//posts
export const FETCH_POST_LOADING = "FETCH_POST_LOADING";
export const FETCH_POST = "FETCH_POST";
export const LATEST_POST = "LATEST_POST";
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_LOADING = "CREATE_POST_LOADING";
export const FETCH_POST_ERRORS = "FETCH_POST_ERRORS";
export const CLEAR_POST_ERRORS = "CLEAR_POST_ERRORS";
export const FETCH_SLIDER_POSTS = "FETCH_SLIDER_POSTS";
export const FIND_SLIDER_POST = "FIND_SLIDER_POST";
export const SEARCH_PRODUCT_QUERY = "SEARCH_PRODUCT_QUERY";
export const FETCH_FEATURED_POSTS = "FETCH_FEATURED_POSTS";
export const FETCH_HOMEPAGE_POST = "FETCH_HOMEPAGE_POST";
//promo
export const FETCH_PROMO_PRODUCTS = "FETCH_PROMO_PRODUCTS";
export const PROMO_PRODUCTS_ERRORS = "PROMO_PRODUCTS_ERRORS";
export const CLEAR_PROMO_PRODUCTS_ERRORS = "CLEAR_PROMO_PRODUCTS_ERRORS";
export const SAVING_PROMO_LOADING = "SAVING_PROMO_LOADING";
//pages
export const FETCH_PAGES = "FETCH_PAGES";
export const FETCH_PAGE_LOADING = "FETCH_PAGE_LOADING";
export const CREATE_PAGE = "CREATE_PAGE";
export const CREATE_PAGE_LOADING = "CREATE_PAGE_LOADING";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const DESTROY_AGE = "DESTROY_AGE";
export const FIND_PAGE = "FIND_PAGE";
export const LOAD_UNILOADER = "LOAD_UNILOADER";
//orders
export const FETCH_ORDERS = "FETCH_ORDERS";
export const DESTROY_ORDER = "DESTROY_ORDER";
export const CHECKOUT_ADDRESS_LOADING = "CHECKOUT_ADDRESS_LOADING";
export const CHECKOUT_ADDRESS_ERRORS = "CHECKOUT_ADDRESS_ERRORS";
export const CLEAR_CHECKOUT_ADDRESS_ERRORS = "CLEAR_CHECKOUT_ADDRESS_ERRORS";
export const PAYMENT_LOADING = "PAYMENT_LOADING";
export const PAYMENT_DATA = "PAYMENT_DATA";
export const FIND_LATEST_ORDER = "FIND_LATEST_ORDER";
export const FIND_ORDER_LOADING = "FIND_ORDER_LOADING";
export const DESTROY_PRODUCT = "DESTROY_PRODUCT";
export const CREATE_ORDER = "CREATE_ORDER";
export const FETCH_ORDER_LOADING = "FETCH_ORDER_LOADING";
export const FIND_USER_ORDERS = "FIND_USER_ORDERS";
export const FETCH_ORDERS_STATUS = "FETCH_ORDERS_STATUS";
export const FETCHING_USER_ORDERS = "FETCHING_USER_ORDERS";
//categories
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CATEGORY_ERRORS = "CATEGORY_ERRORS";
export const CLEAR_CATEGORY_ERRORS = "CLEAR_CATEGORY_ERRORS";
export const CREATING_CATEGORY = "CREATING_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCHING_CATEGORY = "FETCHING_CATEGORY";
//cartlist
export const FETCH_CARTLIST = "FETCH_CARTLIST";
export const CREATE_CARTLIST = "CREATE_CARTLIST";
export const FETCH_PROCESSED_CARTLIST = "FETCH_PROCESSED_CARTLIST";
export const DESTROY_CARTLIST = "DESTROY_CARTLIST";
//shipping
export const FETCH_SHIPPING_PRODUCT = "FETCH_SHIPPING_PRODUCT";
export const CREATE_SHIPPING_PRODUCT = "CREATE_SHIPPING_PRODUCT";
export const UPDATE_SHIPPING_PRODUCT = "UPDATE_SHIPPING_PRODUCT";
export const CREATE_SHIPPING_LOADING = "CREATE_SHIPPING_LOADING";
export const UPDATE_SHIPPING_LOADING = "UPDATE_SHIPPING_LOADING";
//addresses
export const FIND_ADDRESS = "FIND_ADDRESS";
export const UPDATE_CHECKOUT_ADDRESS = "UPDATE_CHECKOUT_ADDRESS";
export const SAVE_CHECKOUT_ADDRESS = "SAVE_CHECKOUT_ADDRESS";
//settings
export const FETCH_SETTINGS = "FETCH_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const CREATE_SETTINGS = "CREATE_SETTINGS";
export const UPDATE_SETTINGS_LOAD = "UPDATE_SETTINGS_LOAD";
//customers
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_CUSTOMERS_LOADING = "FETCH_CUSTOMERS_LOADING";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const CREATE_CUSTOMER_LOADING = "CREATE_CUSTOMER_LOADING";
export const CUSTOMER_ERRORS = "CUSTOMER_ERRORS";
export const CLEAR_CUSTOMER_ERRORS = "CLEAR_CUSTOMER_ERRORS";
export const FIND_CUSTOMER = "FIND_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_LOADING = "UPDATE_CUSTOMER_LOADING";
//cities
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCHING_CITIES = "FETCHING_CITIES";
//regions
export const FETCH_STATE_REGIONS = "FETCH_STATE_REGIONS";
export const SHOW_STATE_REGIONS = "SHOW_STATE_REGIONS";
//billing
export const FIND_BILLING = "FIND_BILLING";
export const FIND_BILLING_LOADING = "FIND_BILLING_LOADING";
//search
export const SEARCH_PROMO_PRODUCT_QUERY = "SEARCH_PROMO_PRODUCT_QUERY";
//locations
export const SHOW_PICKUP_LOCATION = "SHOW_PICKUP_LOCATION";
export const SHOWING_PICKUP_LOCATION = "SHOWING_PICKUP_LOCATION";
export const SETTING_PICKUP_LOCATION = "SETTING_PICKUP_LOCATION";
export const USER_PICKUP_LOCATION = "USER_PICKUP_LOCATION";
